---
driver:
  name: docker

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
      - recipe[example-cookbook::default]
      - recipe[example-cookbook::_audit_default]
    attributes:
